name: moapp_team_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-27.0.dev <4.0.0'

dependencies:
  chat_bubbles: ^1.5.0
  cloud_firestore: ^4.13.0
  firebase_auth: ^4.9.0
  firebase_core: ^2.22.0
  firebase_storage: ^11.5.2
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.6
  image_picker: ^1.0.4
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/temp_profile/kitty.png
    - assets/temp_profile/doggy.png
