name: moapp_team_project
description: A new Flutter project.
publish_to: none
version: 0.1.0
environment:
  sdk: '>=3.1.0-27.0.dev <4.0.0'
dependencies:
  chat_bubbles: ^1.5.0
  cloud_firestore: ^4.13.0
  dart_openai: ^4.0.0
  firebase_auth: ^4.9.0
  firebase_core: ^2.22.0
  firebase_storage: ^11.5.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  google_sign_in: ^6.1.6
  image_picker: ^1.0.4
  provider: ^6.1.1
  toggle_switch: ^2.1.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.0+2
  font_awesome_flutter: ^10.6.0
  onboarding: ^3.1.0
  intl: ^0.18.1
  async: ^2.11.0
  google_mlkit_face_detection: ^0.9.0
  google_mlkit_commons: ^0.6.1
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  url_launcher: ^6.2.1
  flip_card: ^0.7.0
  tuple: ^2.0.2
  flutter_local_notifications: null
  date_format: ^2.0.7
  timer_builder: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/profile1.png
    - assets/temp_profile/kitty.png
    - assets/temp_profile/doggy.png
    - assets/config/.env
    - assets/icons/help.png
    - assets/icons/exit.png
    - assets/icons/filter.png
    - assets/images/1313.png
    - assets/images/google_map_chat.png
